apiVersion: v1
kind: Pod
metadata:
  name: t101-supertest
  labels:
    app: t101-supertest
spec:
  containers:
    - name: container
      image: docker.pkg.github.com/dltdojo/xidunku/t101-supertest
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: t101-supertest
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: t101-supertest

