FROM docker.io/rabbitmq:management-alpine
# https://github.com/docker-library/rabbitmq/blob/master/3.8/alpine/Dockerfile
# https://github.com/docker-library/rabbitmq/blob/master/3.8/alpine/management/Dockerfile
# ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
# CMD ["rabbitmq-server"]