apiVersion: v1
kind: Pod
metadata:
  name: xidunku-xctixweb
  labels:
    app: xidunku-xctixweb
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: server
      image: localhost:32000/xidunku-xctixweb
      ports:
        - name: web
          containerPort: 8443
      command:
      - /usr/bin/dumb-init
      - --
      args:
      - bash
      - -c
      - |
        /xctixweb
        # ?? remove this line will trigger the ERROR 
        # webterm Unable to spawn child: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
