apiVersion: v1
kind: Pod
metadata:
  name: xidunku-xhoami
  labels:
    app: xidunku-xhoami
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: server
      image: localhost:32000/xidunku-xhoami
      ports:
        - name: web
          containerPort: 80
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
