apiVersion: skaffold/v2alpha1
kind: Config
build:
  insecureRegistries:
  - localhost:32000
  artifacts:
  - image: localhost:32000/msgsys-email
    context: email
deploy:
  kubectl:
    manifests:
      - email/k8s-pod-slowcat.yaml
profiles:
- name: smtpx1
  build:
    artifacts:
    - image: localhost:32000/msgsys-email
      context: email
  deploy:
    kubectl:
      manifests:
        - email/k8s-pod-slowcat.yaml
- name: smtpx2
  build:
    artifacts:
    - image: localhost:32000/msgsys-email
      context: email
  deploy:
    kubectl:
      manifests:
        - email/k8s-pod-smtpx2.yaml
- name: rabbitmq
  build:
    artifacts:
    - image: localhost:32000/msgsys-rabbitmq
      context: rabbitmq
  deploy:
    kubectl:
      manifests:
        - rabbitmq/k8s-pod.yaml
  portForward:
    - resourceType: Pod
      resourceName: msgsys-rabbitmq
      address: 0.0.0.0
      port: 15672
      localPort: 15672
    - resourceType: Pod
      resourceName: msgsys-rabbitmq2
      address: 0.0.0.0
      port: 15672
      localPort: 15673
- name: rabbitmq-dev
  build:
    artifacts:
    - image: localhost:32000/msgsys-rabbitmq
      context: rabbitmq
    - image: localhost:32000/msgsys-rabbitmq-cli
      context: rabbitmq/client-js
  deploy:
    kubectl:
      manifests:
        - rabbitmq/k8s-pod-dev.yaml
        - rabbitmq/client-js/k8s-pod.yaml
  portForward:
    - resourceType: Pod
      resourceName: msgsys-rabbitmq
      address: 0.0.0.0
      port: 15672
      localPort: 15672